DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('ds_preview_form_label','Vorschau','position',0,'column_name','column_name','position',1,'','','','',0,'cellmodel','',0,'','','view_readtable_ds_preview_form_label_all','Datenstamm','',1,'','','listview','XlsxWriter','{GUID}',0,100,0,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic') ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
INSERT  IGNORE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('ds_preview_form_label','active',NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'YES',NULL,1,NULL,'tinyint','','tinyint(4)',NULL,3,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('ds_preview_form_label','column_name',NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','PRI','varchar(64)',64,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('ds_preview_form_label','dockposition','left',0,0,'',0,0,'','','YES','',1,'','varchar','','varchar(20)',20,0,0,'utf8mb4','select,insert,update,references',1,0,'',''),
('ds_preview_form_label','editor',NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(100)',100,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('ds_preview_form_label','field_path','',0,0,'',0,0,'','','NO','NO',1,'','varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,NULL,''),
('ds_preview_form_label','label',NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('ds_preview_form_label','language','DE',0,0,'',1,0,'','','NO','',1,'','varchar','PRI','varchar(3)',3,0,0,'utf8mb4','select,insert,update,references',1,0,'',''),
('ds_preview_form_label','position','9999',0,0,'',0,0,'','','YES','',1,'','int','','int(11)',0,10,0,'','select,insert,update,references',1,0,'',''),
('ds_preview_form_label','table_name',NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','PRI','varchar(128)',128,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('ds_preview_form_label','xtype',NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,'');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('ds_preview_form_label','active','DE','Aktiv','gridcolumn','',6,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('ds_preview_form_label','column_name','DE','Spalte','gridcolumn','',1,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('ds_preview_form_label','dockposition','DE','Dock-Position','gridcolumn',NULL,8,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('ds_preview_form_label','editor','DE','editor','gridcolumn',NULL,7,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('ds_preview_form_label','field_path','DE','Pfad','gridcolumn','',5,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('ds_preview_form_label','label','DE','Label','gridcolumn','textfield',3,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('ds_preview_form_label','language','DE','Sprache','gridcolumn','',2,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('ds_preview_form_label','position','DE','Position','gridcolumn','',9,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('ds_preview_form_label','table_name','DE','Tabelle','gridcolumn','',0,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('ds_preview_form_label','xtype','DE','Typ','gridcolumn','formxtype_combobox',4,'','','',0,1,'',0,1.00,'ASC','left','',NULL);
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('ds_preview_form_label','active','DE','Aktiv','checkbox','Allgemein/Angaben',6,0,1,1,'',1.00,'\'\''),
('ds_preview_form_label','column_name','DE','Spalte','displayfield','Allgemein/Angaben',1,1,1,1,'',1.00,'\'\''),
('ds_preview_form_label','dockposition','DE','Dock-Position','displayfield','Allgemein/Angaben',8,0,1,1,'',1.00,'\'\''),
('ds_preview_form_label','editor','DE','editor','displayfield','Allgemein/Angaben',7,0,1,0,'',1.00,'\'\''),
('ds_preview_form_label','field_path','DE','Pfad','displayfield','Allgemein/Angaben',5,1,1,1,'',1.00,'\'\''),
('ds_preview_form_label','label','DE','Label','textfield','Allgemein/Angaben',3,0,1,1,'',1.00,'\'\''),
('ds_preview_form_label','language','DE','Sprache','displayfield','Allgemein/Angaben',2,1,1,1,'',1.00,'\'\''),
('ds_preview_form_label','position','DE','Position','displayfield','Allgemein/Angaben',9,1,1,1,'',1.00,'\'\''),
('ds_preview_form_label','table_name','DE','Tabelle','displayfield','Allgemein/Angaben',0,1,1,1,'',1.00,'\'\''),
('ds_preview_form_label','xtype','DE','Typ','formxtype_combobox','Allgemein/Angaben',4,0,1,1,'',1.00,'\'\'');
INSERT  IGNORE INTO `ds_reference_tables` (`table_name`, `reference_table_name`, `columnsdef`, `constraint_name`, `active`, `searchable`, `autosync`, `position`, `path`, `existsreal`, `tabtitle`) VALUES ('ds_preview_form_label','ds','{\"table_name\":\"table_name\"}','fk_ds_preview_form_label_ds',1,0,1,99999,'',1,'');
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append` ) VALUES ('administration','ds_preview_form_label',1,1,0,0);
