#!/bin/bash

DATA=$(mysqldump --complete-insert --no-create-info --tables ${@:2} ds --where "table_name = '$1'")
./remove_info "$DATA"
DATA=$(mysqldump --complete-insert --no-create-info --tables ${@:2} ds_column --where "table_name = '$1'")
./remove_info "$DATA"
DATA=$(mysqldump --complete-insert --no-create-info --tables ${@:2} ds_column_list_label --where "table_name = '$1'")
./remove_info "$DATA"
DATA=$(mysqldump --complete-insert --no-create-info --tables ${@:2} ds_column_form_label --where "table_name = '$1'")
./remove_info "$DATA"
DATA=$(mysqldump --complete-insert --no-create-info --tables ${@:2} ds_dropdownfields --where "table_name = '$1'")
./remove_info "$DATA"
DATA=$(mysqldump --complete-insert --no-create-info --tables ${@:2} ds_reference_tables --where "table_name = '$1'")
./remove_info "$DATA"
DATA=$(mysqldump --complete-insert --no-create-info --tables ${@:2} ds_addcommands --where "table_name = '$1'")
./remove_info "$DATA"