#!/bin/bash
cd -P -- "$(dirname -- "$0")"
TABLES=`cat << EndOfTables
ds
ds_access
ds_listplugins
ds_privacy_rating_types
ds_privacy_rating
ds_addcommand_locations
ds_addcommands
ds_addcommands_xtypes
ds_additional_columns
ds_class
ds_column
ds_column_form_label
ds_column_forcetype
ds_form_properties
ds_column_form_properties
ds_column_list_export
ds_column_list_label
ds_column_tagfields
ds_column_types
ds_blg_column
ds_combined_tables
ds_contextmenu
ds_contextmenu_groups
ds_contextmenu_params
ds_contextmenu_session_groups
ds_custom_listview_config
ds_db_types_fieldtype
ds_dropdownfields
ds_export_file_transfer
ds_import_file_transfer
ds_nm_tables
ds_preview_form_label
ds_pug_templates
ds_referenced_manual
ds_referenced_manual_columns
ds_reference_tables
ds_renderer
ds_renderer_stylesheet_groups
ds_renderer_stylesheet
ds_renderer_stylesheet_attributes
ds_renderer_stylesheet_groups_assign
ds_searchfields
ds_send_mail
ds_send_mail_to
ds_statistics
ds_sync_data
ds_trigger
ds_used_tables
preisorientierung
lager
blg_config
EndOfTables`

#
# vertriebsregion
#geschaeftsstellen
#geschaeftsstellen_logins
#buchungskreise
#buchungskreise_logins

DATA_TABLES=`cat << EndOfDataTables
ds_addcommand_locations
ds_column_forcetype
ds_privacy_rating_types
EndOfDataTables
`

DS_CONFIG_TABLES=`cat << EndOfTables
ds
ds_access
ds_listplugins
ds_privacy_rating_types
ds_privacy_rating
ds_addcommand_locations
ds_addcommands
ds_addcommands_xtypes
ds_additional_columns
ds_blg_column
ds_class
ds_column
ds_column_form_label
ds_column_form_properties
ds_column_list_export
ds_column_list_label
ds_column_tagfields
ds_column_types
ds_column_forcetype
ds_combined_tables
ds_contextmenu
ds_contextmenu_groups
ds_contextmenu_params
ds_contextmenu_session_groups
ds_custom_listview_config
ds_db_types_fieldtype
ds_dropdownfields
ds_export_file_transfer
ds_form_properties
ds_import_file_transfer
ds_nm_tables
ds_preview_form_label
ds_pug_templates
ds_referenced_manual
ds_referenced_manual_columns
ds_reference_tables
ds_renderer
ds_renderer_stylesheet
ds_renderer_stylesheet_attributes
ds_renderer_stylesheet_groups
ds_renderer_stylesheet_groups_assign
ds_searchfields
ds_statistics
ds_sync_data
ds_trigger
ds_used_tables
EndOfTables`



VIEWS=`cat << EndOfViews
ds_renderer_stylesheet_attributes_dd
view_config_ds
view_config_ds_column
view_readtable_ds
view_readtable_ds_access_all
view_readtable_ds_column
view_readtable_ds_column_form_label
view_readtable_ds_column_list_export
view_readtable_ds_column_list_label_all
view_readtable_ds_column_tagfields
view_readtable_ds_custom_listview_config
view_readtable_ds_preview_form_label_all
view_readtable_ds_referenced_manual
view_readtable_ds_referenced_manual_columns
view_readtable_ds_renderer_stylesheet
view_readtable_ds_renderer_stylesheet_groups
view_readtable_ds_renderer_stylesheet_groups_assign
view_readtable_ds_searchfields
view_readtable_ds_statistics
view_readtable_ds_used_tables
EndOfViews`

DDL=$(./export_table_definition $* $TABLES)
./remove_info "$DDL"
./export_view_definition "$VIEWS" $* 



DATA=$(mysqldump --no-create-info \
--complete-insert \
--single-transaction \
--add-drop-table=false \
--tables $* $DATA_TABLES)
./remove_info "$DATA"

echo "set foreign_key_checks=0;"
for i in $DS_CONFIG_TABLES
do : 
  ./dump_ds_definition $i $*
done

for i in $TABLES
do : 
  ./dump_ds_access $i $*
done
echo "set foreign_key_checks=1;"


 

