#!/bin/bash

for i in $1
do : 
    DDL=$(mysql ${@:2} --skip-column-names --batch -e "select * from information_schema.views where table_schema = database() and table_name='$i'")
    if [[ "" == "$DDL" ]]; then


        mysqldump ${@:2} --compact --no-data --add-drop-table=false --tables $1 \
        | grep -v "!40101" \
        |sed -e 's/ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci//' \
        |sed -e 's/CREATE TABLE/CREATE TABLE IF NOT EXISTS/'

    fi
done

  